name: Release

on:
    push:
        branches: [ main ]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: 'write'
            pull-requests: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Volta
                uses: volta-cli/action@v4

            -   name: Install dependencies
                run: yarn install --immutable

            -   name: Create Release Pull Request or Publish to npm
                uses: changesets/action@v1
                with:
                    publish: yarn publish
                    version: yarn version
                    commit: 'chore: release'
                    title: 'chore: release'
                env:
                    YARN_ENABLE_IMMUTABLE_INSTALLS: false
                    GITHUB_TOKEN: ${{ secrets.HEXATOOL_GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.HEXATOOL_NPM_TOKEN }}
